name: indigo_mfa
description: Indigo Authenticator Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^3.5.5
  permission_handler: ^11.0.0
  # Crypto
  cryptography: ^2.5.0
  asn1lib: ^1.4.0 # For PEM encoding if needed, or manual

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
